id: IA974799B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:35:22+00:00'
last_modified: '2022-06-07T13:39:12.118723+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13432
  title: ཀློང་ཆེན་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2E27:
      image_group_id: I1KG13741
      title: ''
      total_pages: 540
      order: 1
      base_file: 2E27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
