id: P000759
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13432
  title: ཀློང་ཆེན་ཆོས་འབྱུང་།
  author: ''
  volumes:
    09271c4b2a2d4cf7b9332f7afd8e4e76:
      image_group_id: I1KG13741
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
